/*
	Code generated by config2go(https://github.com/xylonx/config2go)
	DON EDIT!
*/
package config

type Setting struct {
	Watch         string   `mapstructure:"watch" json:"watch"`
	SourceConfig  string   `mapstructure:"source_config" json:"source_config"`
	TargetFile    string   `mapstructure:"target_file" json:"target_file"`
	TargetPackage string   `mapstructure:"target_package" json:"target_package"`
	Tag           string   `mapstructure:"tag" json:"tag"`
	Tags          []string `mapstructure:"tags" json:"-"`
}
